header:
  version: 14

repos:
  poky:
    url: https://git.yoctoproject.org/poky
    branch: scarthgap
    path: build/yocto/sources/poky
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-rust-bin:
    url: https://github.com/rust-embedded/meta-rust-bin.git
    branch: master
    path: build/yocto/sources/meta-rust-bin
    layers:
      .:

  meta-template-buildsandbox:
    path: bsp/yocto/layers/meta-template-buildsandbox
    layers:
      .:

env:
  TEMPLATE_VERSION:
  TEMPLATE_BUILD_VERSION:
  TAR_OPTIONS:
  SOURCE_BRANCH:
  SOURCE_REV:
  SMOKE_CORE_EXTERNALSRC:
  RUST_VERSION:
  GIT_SSH_COMMAND:

local_conf_header:
  common: |
    DL_DIR ?= "${TOPDIR}/../../downloads"
    SSTATE_DIR ?= "${TOPDIR}/../../sstate-cache"
    BB_NUMBER_THREADS ?= "${@oe.utils.cpu_count()}"
    PARALLEL_MAKE ?= "-j ${@oe.utils.cpu_count()}"
    RUST_VERSION ?= "1.94.0"
    PREFERRED_VERSION_rust-bin = "${RUST_VERSION}"
    PREFERRED_VERSION_cargo-bin = "${RUST_VERSION}"
    BB_ENV_PASSTHROUGH_ADDITIONS:append = " TEMPLATE_VERSION TEMPLATE_BUILD_VERSION TAR_OPTIONS SOURCE_BRANCH SOURCE_REV SMOKE_CORE_EXTERNALSRC RUST_VERSION GIT_SSH_COMMAND"
